Cache cleanup

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -51,73 +51,97 @@ on:
         type: string
         default: ''
 
+env:
+  CACHE_KEY_PREFIX: ${{inputs.os}}-${{inputs.bazel_mode}}_${{inputs.compiler}}_${{inputs.llvm_version}}_${{inputs.gcc_version}}_${{inputs.bazel_config}}_${{inputs.module_version}}
+
 jobs:
   test:
-    runs-on: ${{ inputs.os }}
-    continue-on-error: ${{ inputs.continue-on-error }}
+    runs-on: ${{inputs.os}}
+    continue-on-error: ${{inputs.continue-on-error}}
     steps:
       - uses: actions/checkout@v4
       - uses: bazelbuild/setup-bazelisk@v3
       - uses: egor-tensin/setup-gcc@v1
-        if: ${{ inputs.compiler == 'gcc' }}
+        if: ${{inputs.compiler == 'gcc'}}
         with:
-          version: ${{ inputs.gcc_version }}
-          platform: x64
+          version: ${{inputs.gcc_version}}
+          platform: ${{runner.arch}}
+
       - uses: actions/cache@v4
         with:
             path: "~/.cache/bazel"
-            key: ${{ inputs.os }}-${{ inputs.bazel_mode }}${{ inputs.compiler }}${{ inputs.llvm_version }}${{ inputs.gcc_version }}${{ inputs.bazel_config }}${{ inputs.module_version }}-${{github.ref}}-${{ github.sha }}
+            key: ${{env.CACHE_KEY_PREFIX}}-${{github.ref}}-${{github.sha}}
             restore-keys: |
-                ${{ inputs.os }}-${{ inputs.bazel_mode }}${{ inputs.compiler }}${{ inputs.llvm_version }}${{ inputs.gcc_version }}${{ inputs.bazel_config }}${{ inputs.module_version }}-${{github.ref}}-
-                ${{ inputs.os }}-${{ inputs.bazel_mode }}${{ inputs.compiler }}${{ inputs.llvm_version }}${{ inputs.gcc_version }}${{ inputs.bazel_config }}${{ inputs.module_version }}-refs/heads/main-
-                ${{ inputs.os }}-${{ inputs.bazel_mode }}${{ inputs.compiler }}${{ inputs.llvm_version }}${{ inputs.gcc_version }}${{ inputs.bazel_config }}${{ inputs.module_version }}-
+              ${{env.CACHE_KEY_PREFIX}}-${{github.ref}}
+              ${{env.CACHE_KEY_PREFIX}}-refs/heads/main
+              ${{env.CACHE_KEY_PREFIX}}
       - run: |
           declare -a BAZEL_INIT=()
           declare -a BAZEL_ARGS=()
-          if [ "${{ inputs.os }}" == "macos-latest" ]; then
-            CACHE_ROOT=~/.cache/bazel
-            BAZEL_INIT+=("--output_user_root=${CACHE_ROOT}")
-            BAZEL_ARGS+=("--repository_cache=${CACHE_ROOT}/repo-cache")
-          fi
-          if [ "${{ inputs.bazel_mode}}" == "workspace" ]; then
+          CACHE_ROOT=~/.cache
+          BAZEL_INIT+=("--output_user_root=${CACHE_ROOT}/bazel")
+          BAZEL_ARGS+=("--repository_cache=${CACHE_ROOT}/bazel_repo-cache")
+          if [ "${{inputs.bazel_mode}}" == "workspace" ]; then
             BAZEL_ARGS+=("--noenable_bzlmod" "--enable_workspace")
-          elif [ "${{ inputs.bazel_mode}}" == "bzlmod" ]; then
+          elif [ "${{inputs.bazel_mode}}" == "bzlmod" ]; then
             BAZEL_ARGS+=("--enable_bzlmod" "--noenable_workspace")
           else
             echo "ERROR: Matrix/Input var 'bazel_mode' must be one of [bzlmod, workspace]."
             exit 1
           fi
-          if [ "${{ inputs.compiler }}" == "clang" ]; then
+          if [ "${{inputs.compiler}}" == "clang" ]; then
             BAZEL_ARGS+=("--config=clang")
             unset CC
             unset CXX
-            if [ -r "bazelmod/llvm.${{ inputs.llvm_version }}.MODULE.bazel" ]; then
-              cp "bazelmod/llvm.${{ inputs.llvm_version }}.MODULE.bazel" bazelmod/llvm.MODULE.bazel
-            elif [ -n "${{ inputs.llvm_version }}" ]; then
+            if [ -r "bazelmod/llvm.${{inputs.llvm_version}}.MODULE.bazel" ]; then
+              cp "bazelmod/llvm.${{inputs.llvm_version}}.MODULE.bazel" bazelmod/llvm.MODULE.bazel
+            elif [ -n "${{inputs.llvm_version}}" ]; then
               CONTROL_FILE=bazelmod/llvm.MODULE.bazel
-              sed -e 's,llvm_version = ".*",llvm_version = "${{ inputs.llvm_version }}",g' "${CONTROL_FILE}" > "${CONTROL_FILE}.new"
+              sed -e 's,llvm_version = ".*",llvm_version = "${{inputs.llvm_version}}",g' "${CONTROL_FILE}" > "${CONTROL_FILE}.new"
               mv "${CONTROL_FILE}.new" "${CONTROL_FILE}"
             fi
-          elif [ "${{ inputs.compiler}}" == "gcc" ]; then
+          elif [ "${{inputs.compiler}}" == "gcc" ]; then
             export CC=/usr/local/bin/gcc
             export CXX=/usr/local/bin/g++
           else
             echo "ERROR: Matrix/Input var 'compiler' must be one of [clang, gcc]."
           fi
-          if [ "${{ inputs.bazel_config }}" == "asan" ]; then
+          if [ "${{inputs.bazel_config}}" == "asan" ]; then
             BAZEL_ARGS+=("-c" "dbg" "--config=asan")
-          elif [ "${{ inputs.bazel_config }}" == "cpp23" ]; then
+          elif [ "${{inputs.bazel_config}}" == "cpp23" ]; then
             BAZEL_ARGS+=("-c" "opt" "--config=cpp23")
-          elif [ "${{ inputs.bazel_config }}" == "fastbuild" ]; then
+          elif [ "${{inputs.bazel_config}}" == "fastbuild" ]; then
             BAZEL_ARGS+=("-c" "fastbuild")
-          elif [ "${{ inputs.bazel_config }}" == "opt" ]; then
+          elif [ "${{inputs.bazel_config}}" == "opt" ]; then
             BAZEL_ARGS+=("-c" "opt")
           else
-            echo "ERROR: Matrix/Input var 'bazel_config' must be one of [asan, fastbuild, opt]."
+            echo "ERROR: Matrix/Input var 'bazel_config' must be one of [asan, cpp23, fastbuild, opt]."
           fi
-          if [ -n "${{ inputs.module_version }}" ]; then
-            cp "bazelmod/MODULE.${{ inputs.module_version }}.bazel" MODULE.bazel
+          if [ -n "${{inputs.module_version}}" ]; then
+            cp "bazelmod/MODULE.${{inputs.module_version}}.bazel" MODULE.bazel
           fi
           echo "BAZEL_INIT: ${BAZEL_INIT[@]}"
           echo "BAZEL_ARGS: ${BAZEL_ARGS[@]}"
           bazel "${BAZEL_INIT[@]}" test "${BAZEL_ARGS[@]}" //...
+
+  cleanup:
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    needs: test
+    steps:
+      - name: Cleanup old caches
+        run: |
+          set -euo pipefail
+
+          PREFIX="${{env.CACHE_KEY_PREFIX}}-${{github.ref}}"
+          echo "Fetching list of old caches for key prefix '${PREFIX}''..."
+          cacheKeyList=$(gh cache list  --limit 250 --json id,key,ref,createdAt --jq "map(select(.key|startswith(\"${PREFIX}\")))|sort_by(.createdAt)|.[:-1]|.[].id")
+
+          echo "Deleting caches..."
+          for cacheKey in ${cacheKeyList}; do
+            echo "Deleting cache: '${cacheKey}'"
+            gh cache delete "${cacheKey}" || echo "Error deleting: '${cacheKey}'."
+          done
+        env:
+          GH_TOKEN: ${{secrets.CACHE_ACCESS}}
+          GH_REPO: ${{github.repository}}
