Improve StringifyOptions (#155)
* Improve StringifyOptions
* Group struct into several aspects.
* Each aspect can be one of:
  * A nullopt in which case core defaults or context dependent defaults will be used.
  * A const reference.
  * An actual value.
Improve OptionalDataOrRef
* Implement `get()` which returns the value if present or a static default.
Improve OptionalRef
* Move run-time checks to `value()` so they cover all cases.
Added
* IsSameAsAnyOf

* Bump minimum GCC to 13.
* Added Demangle
* improved macos support

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -116,8 +116,12 @@ jobs:
             export CXX=/usr/local/bin/g++
           elif [ "${{inputs.compiler}}" == "native" ]; then
             # Use whatever is found!
-            [ -n "${CC}" ] && [ -x "${CC}" ] && echo "CC: $(${CC} --version)"
-            [ -n "${CXX}" ] && [ -x "${CXX}" ] && echo "CXX: $(${CXX} --version)"
+            if [ -n "${CC}" ] && [ -x "${which gcc}" ]; then
+              export CC="${which gcc}"
+            fi
+            if [ -n "${CXX}" ] && [ -x "${which g++}" ]; then
+              export CC="${which g++}"
+            fi
           else
             echo "ERROR: Matrix/Input var 'compiler' must be one of [clang, gcc, native]."
           fi
@@ -137,8 +141,11 @@ jobs:
               cp "bazelmod/MODULE.${{inputs.module_version}}.bazel" MODULE.bazel
             fi
           fi
+          [ -n "${CC}" ] && [ -x "${CC}" ] && echo "CC: $(${CC} --version)"
+          [ -n "${CXX}" ] && [ -x "${CXX}" ] && echo "CXX: $(${CXX} --version)"
           echo "BAZEL_INIT: ${BAZEL_INIT[@]}"
           echo "BAZEL_ARGS: ${BAZEL_ARGS[@]}"
+          bazel "${BAZEL_INIT[@]}" run "${BAZEL_ARGS[@]}" //tools:show_compiler || echo "Cannot determine compiler version!"
           bazel "${BAZEL_INIT[@]}" test "${BAZEL_ARGS[@]}" //...
 
       - uses: actions/cache/save@v4
